"""Generate a sample Wishlist Confidence Brief via Groq."""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from discovery.config import GROQ_API_KEY, GROQ_MODEL_PRIMARY

PRODUCT = {
    "name": "Anouk Women Pink & Gold Woven Design Kurta",
    "brand": "Anouk",
    "category": "Ethnic wear — Kurta",
    "price_inr": 1499,
    "fabric": "Viscose rayon blend",
    "occasion_saved_for": "Friend's wedding (day function)",
    "sizes_available": ["XS", "S", "M", "L", "XL", "XXL"],
    "review_count": 847,
    "avg_rating": 4.1,
}

REVIEWS = [
    {"size_bought": "M", "height_cm": 162, "body": "Perfect for wedding guest. Fabric has a nice fall. I'm 162cm, 58kg — M fits well on shoulders, slightly loose at waist."},
    {"size_bought": "S", "height_cm": 155, "body": "Runs slightly large. Usually wear M in western but S worked. Pink color is exactly like photos."},
    {"size_bought": "L", "height_cm": 168, "body": "Bought L because reviews said sizing up — was too baggy. Should have stuck with M. Quality is good for the price."},
    {"size_bought": "M", "height_cm": 165, "body": "Gold weave looks premium in person. Wore to sangeet — got compliments. Length hits mid-calf on me."},
    {"size_bought": "M", "height_cm": 160, "body": "Fabric is lightweight, good for summer wedding. Not see-through. Sleeves true to size chart."},
    {"size_bought": "S", "height_cm": 158, "body": "Neckline slightly deeper than expected from photos. Fit otherwise fine. Needed minor tailoring at waist."},
    {"size_bought": "XL", "height_cm": 172, "body": "Comfortable for plus size. Doesn't cling. Color slightly brighter than screen."},
    {"size_bought": "M", "height_cm": 163, "body": "Return-free experiment — kept it. True to size chart if you measure bust. Wedding-appropriate."},
]

WISHLIST_COMPARE = [
    {"name": "Sangria Purple Embroidered Kurta", "price_inr": 1899, "fit_sentiment": "mixed — embroidery stiff, runs small"},
    {"name": "Libas Peach Floral Kurta Set", "price_inr": 1299, "fit_sentiment": "positive — true to size, dupatta included"},
]

USER = {
    "height_cm": 163,
    "weight_kg": 58,
    "usual_size_tops": "M",
    "saved_days": 12,
    "occasion_saved_for": "Friend's wedding (day function)",
}

PROMPT = f"""You are generating a Myntra Wishlist Confidence Brief MVP demo output.

PRODUCT:
{json.dumps(PRODUCT, indent=2)}

SAMPLE REVIEWS (synthetic but realistic):
{json.dumps(REVIEWS, indent=2)}

OTHER WISHLIST ITEMS (compare context):
{json.dumps(WISHLIST_COMPARE, indent=2)}

USER CONTEXT:
{json.dumps(USER, indent=2)}

Generate a Confidence Brief exactly as the MVP would show it in-app. Return JSON only:
{{
  "product_name": "...",
  "recommended_size": "...",
  "size_rationale": "one sentence",
  "fit_summary_bullets": ["3-4 bullets synthesizing reviews for someone ~163cm, 58kg, usual M"],
  "fabric_quality_line": "one sentence",
  "occasion_fit": "one sentence for wedding day function",
  "confidence_badge": "Strong match | Good match | Wider stretch",
  "compare_vs_wishlist": "2-3 sentences vs the other 2 saved kurtas — help user pick",
  "why_trust_this": "one sentence on review count / patterns",
  "cta_primary": "Add to Bag",
  "honest_caveat": "one limitation if review data is thin on any dimension"
}}

Rules: No discounts. No fabricated stats — derive from the reviews given. Be specific like real Myntra UX copy. Indian English."""

def main():
    if not GROQ_API_KEY:
        print("NO_GROQ_KEY")
        return 1

    from groq import Groq

    client = Groq(api_key=GROQ_API_KEY)
    resp = client.chat.completions.create(
        model=GROQ_MODEL_PRIMARY,
        messages=[{"role": "user", "content": PROMPT}],
        temperature=0.4,
        response_format={"type": "json_object"},
    )
    text = resp.choices[0].message.content
    out_path = ROOT / "research" / "sample-confidence-brief.json"
    brief = json.loads(text)
    out_path.write_text(json.dumps(brief, indent=2, ensure_ascii=False), encoding="utf-8")

    md_path = ROOT / "research" / "sample-confidence-brief.md"
    md_path.write_text(format_markdown(brief, PRODUCT, USER), encoding="utf-8")
    print(md_path)
    return 0


def format_markdown(brief: dict, product: dict, user: dict) -> str:
    bullets = "\n".join(f"- {b}" for b in brief.get("fit_summary_bullets", []))
    return f"""# Sample MVP — Wishlist Confidence Brief

> **Demo product:** {product['name']} · **Saved {user['saved_days']} days** · **Occasion:** {user['occasion_saved_for']}  
> **Generated by:** Groq ({GROQ_MODEL_PRIMARY}) · **For deck Slide 6 / Part 5 prototype**

---

## How it appears on wishlist (mobile mock copy)

```
┌─────────────────────────────────────────┐
│  ♥ Anouk Pink & Gold Kurta      ₹1,499  │
│  Saved 12 days ago · Wedding guest      │
│                                         │
│  ┌─────────────────────────────────┐    │
│  │ ✨ Confidence Brief              │    │
│  │ Badge: {brief.get('confidence_badge', '—')}          │    │
│  └─────────────────────────────────┘    │
│                                         │
│  Recommended size: {brief.get('recommended_size', '—')}                  │
│  {brief.get('size_rationale', '')}      │
│                                         │
│  What buyers like you say:              │
{chr(10).join('  ' + line for line in bullets.split(chr(10)))}
│                                         │
│  Fabric: {brief.get('fabric_quality_line', '')}  │
│  Occasion: {brief.get('occasion_fit', '')}      │
│                                         │
│  vs your other saves:                   │
│  {brief.get('compare_vs_wishlist', '').replace(chr(10), ' ')} │
│                                         │
│  [ Add to Bag ]    [ Still not sure? ]  │
└─────────────────────────────────────────┘
```

---

## Full Brief (expanded panel)

### Recommended size
**{brief.get('recommended_size', '—')}** — {brief.get('size_rationale', '')}

### Fit summary
{bullets}

### Fabric & quality
{brief.get('fabric_quality_line', '')}

### Occasion fit
{brief.get('occasion_fit', '')}

### Compare with your wishlist
{brief.get('compare_vs_wishlist', '')}

### Trust signal
{brief.get('why_trust_this', '')}

### Honest caveat
{brief.get('honest_caveat', '')}

---

## MVP honesty callouts

| ✓ Real in this demo | ~ Simplified for prototype |
|---------------------|----------------------------|
| Groq-generated synthesis from review inputs | Product/reviews are representative, not live-scraped from Myntra API |
| Matches Confidence Brief spec from Part 5 | User height/weight entered manually, not from Myntra profile |
| Compare block uses wishlist context | Only 3 hardcoded compare items |

---

*Use in deck: screenshot this panel or copy the mock ASCII block.*
"""


if __name__ == "__main__":
    raise SystemExit(main())
